# Generated by Django 4.0 on 2023-04-04 05:23

import ckeditor.fields
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='design_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='design',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='design',
            name='design_photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='design',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Home theatre system', 'Home theatre system'), ('Wooden Floor', 'Wooden Floore'), ('Unbreakable glasses', 'Unbreakable glasses'), ('Air Conditioning', 'Air Conditioning'), ('Heating', 'Heating'), ('Alarm System', 'Alarm System'), ('ParkingGarage', 'ParkingGarage'), ('Solar Powered', 'Solar Powered'), ('Sensor Lights', 'Sensor Lights'), ('Camera System', 'Camera System'), ('Furnished', 'Furnished'), ('Non-Furnished', 'Non-Furnished'), ('Greenhouse', 'Greenhouse')], max_length=181),
        ),
        migrations.AlterField(
            model_name='design',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
