# Generated by Django 4.0 on 2023-04-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_design_design_photo_alter_design_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='floors',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=10),
        ),
        migrations.AddField(
            model_name='design',
            name='squarefeet',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
