# Generated by Django 4.2 on 2023-04-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='linkedin_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
